### ISSUE TITLE
Won't change ip

### ISSUE THREAD

**Issue by TRUBDUBZ** [owerdogan/whoami-project#28]
# **Describe the bug**
I am trying to run kali-whoami on kali linux virtual machine using UTM. I am not having issues with the installation or configuring the program however, when I try to check my IP address with sites like [WhatsMyIP](https://www.whatsmyip.org) and [DNS Leak Test](https://www.dnsleaktest.com) I find that my IP and Location are both still revealed. I have also tried using proxychains.conf and Tor service to try to protect my anonymity but no luck with that either. Only thing that works is VPN.

# **To Reproduce** 
(_This makes bug detection easier_)

- Config Any of the features on Mac M1 kali linux VM using UTM, then check your ip using google

**Expected behavior:** 

It would be expected to hide my identity by changing ip address, dns, and location.

 - OS: [e.g. Kali Linux 2021.2]
 - Tool version [latest install]

**Additional context**
Not sure if this is the right place to ask this but i've tried about everything and hoping to find a fix.

**Comment by owerdogan** [comment]
Hello @TRUBDUBZ,

Don't worry, you're in the right place.

First, thank you for submitting your issue with the right template. Conscious users are very valuable to us.
_I would like to point out that your problem is not caused by the **Whoami Project**._ 
It seems that your problem is caused by censorship or network configuration. To summarize briefly, although both change your IP address, the main difference between VPN and TOR is that they use different protocols. For this reason, VPN can work, but Proxychains can't. 
Assuming the situation is caused by censorship If you have a TOR browser, you can try to connect to TOR with the obfs4 bridge in the settings, but remember that the browser settings do not affect the system. The purpose of doing this is to check whether you are under censorship. If you have detected that you are under censorship you can connect to VPN first and then connect to TOR, or you can configure your system for TOR (with torrc) with a bridge available on their [official site](https://bridges.torproject.org/options).

If your problem still persists, try the part below.

Have you tried it on another virtual machine?
Probably yes, but if you haven't tried, please If you have a different linux distribution, run your test on both distributions and compare the results after that report your result here.
This will facilitate the detection of the problem.

**Comment by TRUBDUBZ** [comment]
I believe i have it narrowed down. Im trying to run this on M1 chip and it's my understanding that you can't run tor browser on M1 chips. I now know that the issue is not with Whoami and more of a compatibility issue with apple silicon chips. Thank you for addressing my issue!
